JasmineRickards/TGMC-PVE

- code/game/objects/items/explosives/grenades/grenade.dm
- code/modules/projectiles/guns/flamer.dm
- code/modules/projectiles/guns/rifles.dm
Defines a caliber for the PR-11 pulse rifle. Turns out the gun is so old that the variable was never added to it.
PR-11 can once again accept its magazines
:cl:
fix: fixed an oversight with the PR-11 lacking its caliber var that was causing it to not be loadable.
/:cl:
> Hotfix for PR-11

- code/modules/projectiles/magazines/specialist.dm
It's in the title
Minigun can link to its powerpack again
:cl:
fix: Minigun can link to its powerpack again
/:cl:
> Fixes Vindicator minigun powerpack

- code/modules/projectiles/magazines/specialist.dm
> Fixes a typo

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/clothing/gloves/marine_gloves.dm
- code/modules/clothing/modular_armor/modular.dm
- code/modules/clothing/shoes/marine_shoes.dm
It's Jaeger, but for robots. I have included the M10x, Helljumper, and Assault helmets in the Golem lineup, but all the other Jaeger helmets currently have a color issue where they appear significantly brighter than the armor pieces do. All the modular armor pieces fit on the exoskeleton. Additionally, combat robots may now wear marine-standard gloves and combat boots.
More customizability is also nice, and the ability to mount modules on robots really shouldn't be that big of a deal since their resistance to brute and weakness to burn was removed ages ago.
:cl:
add: Added Robot-wearable Jaeger exoskeleton and three modular helmets, all referred to as Golem pattern. Look for them in the armor vendor.
code: Allowed robots to wear marine gloves and boots.
/:cl:
> Introducing Golem Pattern Modular Robot Armor

- code/modules/clothing/modular_armor/modular.dm
Hotfix for the Golem Heavy and Golem Open helmets
> Quick fix for two helms

- code/game/objects/items/defibrillator.dm
- code/modules/clothing/gloves/miscellaneous.dm
Allows combat robots to wear latex gloves.
Allows combat robots to wear captain gloves.
Allows combat robots to wear corpsmen defibrillator gloves.
Gives combat robots more options for fashion or corpsman utility.
:cl:
add: combat robots can wear latex gloves and captain gloves.
balance: combat robot corpsmen can now wear and use advanced medical combat gloves.
/:cl:
> more gloves for robots

- code/modules/clothing/modular_armor/modular.dm
- code/modules/reqs/supplypacks.dm
I also forgor to make it attachable to armor. Fixed now, my bad
People can now attach it, also the new name is better
:cl:
fix: Renames Ragnarok in Req to Muspelheimr, and makes it attachable to armor.
/:cl:
> I forgor I changed Ragnarok to Muspelheimr

- code/modules/clothing/glasses/hud.dm
Gives the Xenomate imagers a necessary line of code that I forgor
You should now actually get the benefit of partial nightvision
:cl:
fix: The base Xenomate imagers should now have the same night vision properties as the Optical Imagers
/:cl:
> Adds the Mostly Visible lighting alpha to the Xenomate Imager hug

- code/modules/projectiles/ammo_datums.dm
- code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
- code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
All mech weaponry (or more accurately from a code standpoint, mech ammo) now has IFF properties, allowing the mech to fire past marines. Certain weapons, such as the mech flamer and rocket launcher, still retain incidental effects that can be hazardous to allies.
Most mech weapons have had their damage increased by between 50% and 300% depending on rate of fire and caliber, as well as increases to sundering. The highest sunder weapon is the 30mm airburst cannon on a direct hit, with a bonus projectile count of 7 and 10 sunder per projectile. It is now a weapon designed for taking on behemoth level threats. The mech rocket now does 100 damage on a direct hit, with 50 penetration, and the impact center now counts as devastation, insta-gibbing anything that happens to be on ground zero and …
> Various buffs to mech weaponry

- code/modules/projectiles/guns/energy.dm
Read the title
The fix for the other energy guns to take these cells didn't apply to pistols, this fixes that.
:cl:
fix: You can now use TE standard cells in laspistols, making pistol belts once again worth holding them in.
/:cl:
> Lets laser pistols take TE cells again

- code/datums/skills.dm
That's it.
Tad gaming.
:cl:
qol: Pilot Officers now have about the same level of skill as a mech pilot.
/:cl:
> Allows pilot officers to fix their own shit

- code/datums/jobs/job/upp.dm
- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/marine_armor.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/reqs/supplypacks.dm
Tweaks the UPP armor to be more in line with others, such as being able to take pistol holsters on it's exosuit slots, while the helmet can hold injectors and what not.
Additionally, the PR-11's stock has been restored.
Lastly, RR has been added to req at 100 points/2 bottles.
Beats me.
> Soviet Changes, da! (And the PR-11)

- code/modules/projectiles/guns/rifles.dm
- code/modules/reqs/supplypacks.dm
Makes the 5 point crate mags, not rifles. Changes a colon, adds a scarf and beret.
Unintended 3AM fuck-ups.
> I dunno, fixes, I guess to imports, a colon. And a beret.

- code/modules/projectiles/guns/smgs.dm
grenade luancher on smg25
gre nade launcher on smg25
> half life sm,g

- tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Reverts JasmineRickards/TGMC-PVE#61
> Revert "Revert "Fixes a TGUI bug""

- code/game/objects/items/explosives/grenades/chem_grenade.dm
Unintended, and now fixed.
It squashes a bug
:cl:
fix: Large beakers no longer fit in small grenade casings.
/:cl:
> Fixes large beakers fitting in small grenade cases.

- code/modules/clothing/suits/marine_armor.dm
Allows the PMC gunner exosuit slot to hold guns.
Er....It's not really SG exclusive, so it may aswell have access to guns.
:cl:
/:cl:
> Allows PMC Gunner exosuit slot to hold a bigger variety of items.

- code/game/objects/machinery/vending/loadout_vendor.dm
- code/game/objects/machinery/vending/marine_vending.dm
- code/game/objects/machinery/vending/vending_types.dm
What it says on the tin.
I'm sure you'd appreciate not having to have eyes in the back of your head.
:cl:
/:cl:
> Modifies most non-mobile vendors to be indestructable.

- code/modules/projectiles/gun_attachables.dm
I made a mistake,. the crane stock for the SH-35 has been shifted 1 pxl down so it looks correct now.
> moves crane stock down 1 pxl

- code/modules/projectiles/guns/shotguns.dm
Since Jasmine wanted to hit the SH-35 with the nerf bat again, I am offering a different kind of nerf from making it slow to use. 
Making the pump shotgun slower to use might rein in its DPS, but it also makes the gun less responsive, which is bad in a horde shooter. I would rather chop its damage almost in half than play with this reduction of its fire rate by 350%.
:cl:
balance: Reverts SH-35 fire-delay from 1.4 seconds to 0.4 seconds, but reduces damage multiplier from 2 to 1.25
balance: reduces Paladin firedelay from 1.5 seconds to 1 second. Damage unchanged.
/:cl:
> Changes the nerf of SH-35 from a fire delay nerf to a damage multiplier nerf

- code/game/objects/machinery/vending/marine_vending.dm
- tgmc.dme
It does exactly what it says on the tin
It's drip or drown, fool.
:cl:
code: Both security jumpsuits are in the surplus clothing vendor now, under Standard.
/:cl:
> Adds the two security jumpsuits to the clothing vendor

- code/modules/clothing/modular_armor/modular.dm
Making the Vail module able to be in SOM Armor.
More variety and SOM armor have more armor thus it would be useful on it.
:cl:
add: Made SOM Armor able to use chem system.
> Make SOM armor able to use the vail chem enhancement

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/clothing/modular_armor/attachments/modules.dm
- code/modules/clothing/modular_armor/modular.dm
- code/modules/projectiles/magazines/misc.dm
- code/modules/reqs/supplypacks.dm
- tgmc.dme
Tweaks
Changes some stuff about the MK2, fixes two ammo box types (TL-127 and the Russian burst rifle ammo) that had the same path.
Beats me, it's 2 AM. I want to sleep.
:cl:
/:cl:
> Tweaks the Chemsystem mk2, fixes an ammo box.

- code/modules/clothing/modular_armor/attachments/modules.dm
Makes the chem system better. 
Because it needed that acid resistance.
:cl:
balance: buffed mark 2 chemsystem
/:cl:
> Buff chemsystem mk2

- code/modules/clothing/head/head.dm
- code/modules/clothing/head/jobs.dm
combots get to wear more hats and new title screen thing by yours truely 
species_exception = list(/datum/species/robot)
changed head.dm to allow more hats that combots wear 
changed jobs.dm to allow more hats that combats wear
added a new title screen
> more combot hats and new title screen

- code/game/objects/items/explosives/mine.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures/barricade.dm
- code/modules/ai/presets/xeno_presets.dm
- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/abilities_enemyuv.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/castedatum_iguana.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/gecko/castedatum_gecko.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/gecko/gecko.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/iguana.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/komodo/castedatum_komodo.dm
- code/modules/mob/living/carbon/xenomorph/castes/zuv/komodo/komodo.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/sentries.dm
- code/modules/projectiles/sentries.dm
- tgui/packages/tgui/interfaces/Sentry.tsx
Okie, dokie. Let's get the most important changes out of the way.
Xeno AI will now consider TGMC humans as part of the corrupted hive, this means the Corrupted Hive shouldn't pester the normal marines. (ERTs are fair game for them, however.)
Patches some xeno AI abilities to not cancel mid-channel, namely the UV scatter spit reskins.
Adds a slew of AIs to corrupted xenos, I've kept it relagated to their base type, as to not appear in the middle of the enemy AI spawns. Sure, it's messy. But hey, atleast it reduces butterfingers accidents.
Lastly, tweaked claymore/turret code to not target xenos with the same IFF (Corrupted currently only have this distinction, but it also means we can have enemy AIs throw COPEs in future, for example.)
PS: UVs can now attack cades and mechs, also flashbang …
> A whole slew of AI and Corrupted Xeno related stuff.

- code/datums/jobs/job/survivor.dm
Lets engineers open engineering lockers, gives researchers research access.
:cl:
/:cl:
> Updated survivor accesses

- code/datums/jobs/job/pmc.dm
- code/datums/skills.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/marine_armor.dm
- code/modules/projectiles/guns/energy.dm
Made ERT squad consisting of: ERT team leader, combat medic, field technician and grunt. They have very good equipment and will probably exist for some events or anything like that. There are also some minor changes. Shouldn't effect normal gameplay
More distress and more abilities for events.
:cl:
/:cl:
> Nanotrasen ERT squad and some small changes.

- code/datums/jobs/job/pmc.dm
- code/game/objects/items/storage/marine_boxes.dm
- code/game/objects/items/storage/pouch.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/marine_armor.dm
- code/modules/reqs/supplypacks.dm
Added spec kits for cargo. Cost for each - 100. Some notes about spec armor sets
- Sniper armor can be considered as upgraded light armor
- Scout armor can be considered as upgraded medium armor
- Demolitionist armor can be considered as light EOD armor
- Pyro armor got some tweaks
- B17 armor got some tweaks
Everyone wants to be special. Why not give them a chance to be?
:cl:
/:cl:
> Spec kits for cargo + some changes

- code/game/objects/machinery/vending/vending_types.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/marine_armor.dm
- code/modules/clothing/under/jobs/security.dm
Decided to make SecTech more useful for some events and colony survival. Contains more security gear.
Better life for colonists
:cl:
/:cl:
> Security vendor improvement + some changes

- code/datums/jobs/job/survivor.dm
- code/game/objects/machinery/vending/vending_types.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/head/soft_caps.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/armor.dm
Changed a little my previous PR. Now, all clothings moved to the new SecDrobe. Equipment was left in the SecTech. Some changes to security equipment.
Better life for colonists.
:cl:
/:cl:
> Security vendor and equipment changes

- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/misc.dm
- code/modules/projectiles/magazines/rifles.dm
> M41A MK1 Fixes part 2

- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/specialist.dm
> Another M41A MK1 fix

- code/modules/clothing/masks/gasmask.dm
Quick fix of the gasmask I accidently broke.
:cl:
/:cl:
> Quick fix of gasmask

- code/datums/jobs/access.dm
- code/datums/jobs/job/marines.dm
- code/datums/jobs/job/shipside.dm
New rank system. Most of the roles can now receive more ranks for better understanding who is more experienced.
First Sergeant as marine? Yes please.
:cl:
/:cl:
> Rank System Reform

- code/datums/jobs/job/shipside.dm
- code/datums/jobs/job/special_forces.dm
- code/modules/language/commando.dm
- code/modules/language/language.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
- tgmc.dme
Small addition to the MARSOC - they are now starting with activated tactical language.
Much more tactical squad.
:cl:
/:cl:
> Commando language

- code/game/objects/items/tools/shovel_tools.dm
E-Tools dig twice as fast. Full-size shovels dig twice as fast as e-tools and hold twice as much dirt.
Quality of life for Fobbits.
:cl:
qol: Shovels and e-tools dig faster, and the big shovel holds more dirt.
/:cl:
> Buffs shovel and entrenching tool speed

- code/game/objects/machinery/vending/marine_vending.dm
Simply adds the full-size shovel to the marine vendor.
I forgor to add it in my recent PR, it trades transportability for utility as the superior digging tool.
:cl:
fix: Shovel is now in the marine vendor. Listed as a fix because I forgor to add it.
/:cl:
> Adds the full-size shovel to marine vendor

- code/modules/mining/remote_fob/remote_fob_actions_misc.dm
fob drone builds stuff faster now (0.5 sec per cade)
I know 1.5 seconds per cade doesn't sound like a lot but when your 5 minutes in building the fob and you suddenly have a mental break down you'll understand
:cl:
balance: fob drone builds faster
/:cl:
> fob drone buff

- code/__DEFINES/loadout.dm
- code/game/objects/machinery/vending/new_marine_vendors.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/marine_armor.dm
Added Gorgon armor set to FCs and Leader's vendor. FCs version of Gorgon armor comes with Valkyrie. FCs vendor also gets Krieg's commissar armor aswell (It is stronger than basic Krieg armor).
I got such idea due to the fact, that some roles have requisition equipment tier. So, decided to add those to leaders and FC.
:cl:
/:cl:
> SL and FC vendor addon + Krieg commissar armor set.

- code/modules/clothing/suits/marine_armor.dm
Fixed it's in game name. Now it is correct.
:cl:
fix: fixed a few thingsg
/:cl:
> Commissar's armor quick fix

- code/modules/vehicles/mecha/combat/gygax.dm
- code/modules/vehicles/mecha/combat/phazon.dm
- code/modules/vehicles/mecha/combat/savannah_ivanov.dm
https://github.com/JasmineRickards/TGMC-PVE/issues/124 Combat mechs somehow lost their HAS_HEADLIGHTS flag, this has now been fixed.
Toggle Lights button now fixed
:cl:
fix: Restored the headlights to req mechas
/:cl:
> The exosuits orderable from req have working headlights.

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
- code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Added new abilities and level system for hivemind.
More useful in case you need him in round.
:cl:
/:cl:
> Hivemind update

- code/modules/projectiles/magazines/specialist.dm
Accidentally had the path for the svd magazine and not the svd bullet, and forgor to set the proper caliber for T-127 rifle rounds. Also fixes an unreported typo that would mess with the autosniper caliber setting
:cl:
fix: 7.62x54mmR and 8.6x70mm, and 8.6x70mm Low-Pressure should all work properly with the Marksman belt.
/:cl:
> Fixes three more dumb typos with the marksman belt

- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/magazines/energy.dm
- code/modules/reqs/supplypacks.dm
Made some changed to make M43 more interesting. Now, you can order all lenses with their uses. To put it simple:
1)M43 itself got minor changes to make it worth cost.
2)M43 itself costs less
3) Focus lens cost more, because M43 costs less.
4) Heat lens deals slightly more damage, penetrate enemies. Ment to kill hordes.
5) Wide lens costs like B18. Ment to destroy whatever you need
6) Pulse lens acts as cheap buff for M43:better damage and fire rate. If you'll combine cost with new M43 cost - it'll be the same as old M43 cost.
7)Efficient lens is more overall stat increaser and thus costs more. Also gives you second mode, which have higher AP and can penetrate through enemies.
Makes M43 much more interesting to use.
:cl:
/:cl:
> M43 Energy Rifle changes

- code/datums/jobs/job/shipside.dm
Fixed CMAA rank for time line. Should be working now.
We(I) can get ranks properly.
:cl:
/:cl:
> Quick fix for CMAA rank for time

- code/datums/jobs/job/shipside.dm
Reverts JasmineRickards/TGMC-PVE#186
> Revert "Quick fix for CMAA rank for time"

- code/datums/jobs/job/shipside.dm
Reverts JasmineRickards/TGMC-PVE#187
> Revert "Revert "Quick fix for CMAA rank for time""

- code/datums/jobs/job/shipside.dm
This time it shall work properly
It is very good
:cl:
/:cl:
> Quick fix for CMAA attempt number 2

- code/datums/jobs/job/survivor.dm
- code/datums/skills.dm
- code/game/objects/items/storage/boxes.dm
- code/modules/clothing/spacesuits/rig.dm
A bunch of changes for colonists. Shall improve their gameplay.
Better gameplay for colony survival.
:cl:
/:cl:
> Changes for colonists day 1

- _maps/map_files/Icy_caves_colony/icy_caves_colony.dmm
- _maps/map_files/Research_outpost_colony/Research_Outpost_colony.dmm
- _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
- code/datums/jobs/access.dm
- code/datums/jobs/job/survivor.dm
Some extra changes for colonists and updates for maps.
Some good things.
:cl:
/:cl:
> Colony Survival update day 2

- code/modules/reqs/supplypacks.dm
Your money or your life.
Da
:cl:
/:cl:
> Increased vulcan minigun cost

- code/datums/jobs/job/shipside.dm
- code/datums/skills.dm
Mech pilot has better skills and more ranks to gain.
Mechs are good.
:cl:
/:cl:
> Mech pilot changes

- code/datums/jobs/job/shipside.dm
Fixed mech's pilot rank for time. It was messy before.
Now mech pilots can get ranks properly.
:cl:
/:cl:
> Mech pilot rank time fix
