JasmineRickards/TGMC-PVE

code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/guns/sentries.dm
Some back-end code to make sure all the mounted guns and sentries can be reloaded as per the norm.
Mounted guns won't be broke by the magazine refactor
:cl:
code: Added caliber definitions to mounted guns and sentries. Should be everything that is actually under the purview of magazine-based weapons.
/:cl:
=> Hotfix for mounted guns and sentries

code/modules/projectiles/gun_attachables.dm
This adds an activatable button to the Magnetic Harness, allowing it to act similarly to a pistol lace.
Every time you are forced to drop your gun it gets unlinked from whatever pack you might have hooked it to. The enemy cannot force you to drop your gun if you disable your hand.
:cl:
qol: Magnetic harness can now be used as a lace for any gun that has a usable rail slot and can mount it. Mostly a QoL for powerpack and ammopack users.
/:cl:
=> Allows Mag Harness to act like a pistol lace for longarms.

code/modules/projectiles/magazines/energy.dm
This is to bring the powerpack up to a similar level as the Ammopack for mission longevity. This is 2 percent of max charge every 2 seconds
Where the Ammopack holds a staggering amount of ammo for a relative few guns, the powerpack is compatible with a wider variety and now recharges much faster. You can still run out of shots under constant fire just as the ammopack can (and I have on one occasion), but neither should be viewed as superior to the other now.
:cl:
balance: Powerpack charge amount increased from 32 watts every 2 seconds to 300 watts every 2 seconds
/:cl:
=> Buffs charge rate of Powerpack

code/__DEFINES/mobs.dm, code/modules/projectiles/magazines/energy.dm
…tes. Increase charge delay of m-70 powerpack from 2 seconds to 5 seconds.
Does what it says on the tin
Five minutes from death to permadeath is a really harsh timer with the way the AI will naturally spread out and keep constant pressure on marines. Too harsh when at any time a random warrior can show up and decide, out of a dozen marines, to focus the one dude holding a defib when the guys he's trying to revive are already near permadeath.
Also I unintentionally made Powerpacks charge way too fast, and this should bring them back in line. No more almost infinite overcharge with no meaningful breaks.
:cl:
balance: Defib window increased from 5 minutes to 15
balance: Powerpack charge delay increased from 2 seconds to 5 seconds
/:cl:
=> Buffs defib window, nerfs Powerpack charge delay

code/game/objects/machinery/miner.dm, code/modules/power/groundmap_geothermal.dm
Miner and geothermal generator repair steps now only take 5 seconds each, plus 2.5 second fumble if lacking engineering skill.
Less time forced to stand still and pray some random xeno doesn't decide to focus you means more time for you to shoot at xenos, and less time the admemes need to wait for power to be restored before the marines can get on to other objectives.
:cl:
balance: Repair step time for miners reduced to 5 seconds each, with 2.5 second base fumble if you don't have engineering skill.
balance:Repair step time for geothermal generators reduced to 5 seconds each, with 2.5 second base fumble if you don't have engineering skill.
/:cl:
=> Substantial reduction in the time it takes to repair miners and generators

code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/glasses/hud.dm, code/modules/reqs/supplypacks.dm
The TGMC has come to expect power failures and xeno infestations, and has moved to provide troops with a low-light imager and xenomorph data hud in a single wearable unit. Field testing has also now begun of two sequential improvements on the technology, the first improving on the low-light enhancement technology, and the second improving upon it further and adding terrain highlight functionality via a multistage meson scanner. Should field tests prove successful, the TGMC is considering making the improved imager and multi-stage imager available as standard issue to squad leaders, engineers, and field commanders.
Being able to tell whether or not your enemy is dead beneath a pile of dead bugs is far less of a balance concern when it's not a player on the other end. Besides this, it makes …
=> Combines Xenomate and Optical Imager, adds it to clothing vendor, adds two improved versions to Req.

code/modules/projectiles/guns/mounted.dm
ATR-22 was missing a caliber definition, causing it to be impossible to reload. This fixes it.
Bugfixing, of course.
:cl:
fix: ATR-22 now has a caliber definition, matching that of its ammo. It should now be reloadable.
/:cl:
=> Adds caliber var to ATR-22

code/modules/projectiles/guns/shotguns.dm
Reverts the changes made to the SH-39 in
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10852
Allows all shotguns to be able to be fired with one hand
Does not apply to under barrel shotguns
Shotgun good
:cl:
del: removed GUN_WIELDED_FIRING_ONLY from SH-221
del: removed GUN_WIELDED_FIRING_ONLY from SH-39
del: removed GUN_WIELDED_FIRING_ONLY from sawn-off shotgun
del: removed GUN_WIELDED_FIRING_ONLY from V-51 pump shotgun
del: removed GUN_WIELDED_FIRING_ONLY from V10 pump shotgun
/:cl:
=> shotguns for 1 hand

code/modules/projectiles/guns/shotguns.dm, code/modules/projectiles/magazines/shotguns.dm
Slight increase to internal mag capacity of mosin from 8 rounds to 10. Strip clip capacity increased from 4 to 10. 7.62x54mm box capacity increased from 75 to 200.
Strip clips currently only load half capacity and you can't load another in without the gun being empty. The easiest solution was to match the internal mag capacity with the strip clip capacity. The ammo box buff just brings it in line with other ammo boxes/packets.
:cl:
balance: Mosin max capacity from 8 to 10
balance: 7.62x54 clip capacity from 4 to 10
balance: 7.62x54 box capacity from 75 to 200
/:cl:
=> Mosin buff

code/__DEFINES/calibers.dm, code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/magazines/mounted.dm
Does exactly what it says on the tin
Fixes yet another mounted weapon
:cl:
add: Added a new define, CALIBER_HEAVY_LASER, which should cover any future weapons that use the same caliber as the mounted heavy laser
fix: Mounted Heavy Laser and its ammo now have a caliber definition
/:cl:
=> Fixes heavy laser being unloadable

code/__DEFINES/skills.dm, code/datums/elements/shrapnel_removal.dm, code/datums/jobs/job/marines.dm, code/datums/skills.dm, code/game/objects/items/stacks/barbed_wire.dm, code/game/objects/items/stacks/medical.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/under/marine_uniform.dm, code/modules/reqs/supplypacks.dm
Balance-wise, this is largely meant to ease the burden of the relative few Engineer and Corpsman players in the faster-paced mission styles by giving PFCs more access to basic medical equipment and, particularly, reducing the time dedicated medical roles require to perform their duties. It also adds some more armor options that fit into the broader category of Mercenaries and tweaks some of the defensive equipment at the marines' disposal, halving the cost of barbed wire and making sandbags free from any weapons rack.
Maybe now field hospitals other than (or in addition to) the tadpole will be somewhat viable to do. More teamwork is nice.
:cl:
balance: Squad Marine gains Metal level engineering skill, and the ability to use ATKs, defibs, tweezers, autodoc, and health analyzer without …
=> Increases squad role skills, misc QoL and balance changes, merc drip

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/revolvers.dm
With the recent buff to the HP and/or damage of various minions and other commonly spammed enemy types in order to reign in automatic weapons a bit, most of the pistols, the revolver, and the repeater have lost a substantial level of effectiveness that hurts them far more than it did the automatic rifles.
Weapons that are substantially harder to use effectively than the myriad of automatic weapons need to retain their prior levels of effectiveness, so that it's justifiable to keep them available as more than a gimmick that will more likely than not get you killed.
:cl:
balance: Doubled the damage of handgun and revolver bullets, or slightly less than doubled in a few edge cases
balance: Increased the bullet damage of .45-70 by 20 (effective increase of 40 when fired from the repeater), …
=> Buffs to the ammunition of most single-fire weapons, reintroduction of stagger for various bullets that had it.

code/modules/clothing/suits/marine_armor.dm
Simply adds the NONE flag to map variants for the base veteran armor type, preventing the sprites from being broken by lack of map-specific variants.
It squashes a bug
:cl:
fix: Mercenary armors now have the NONE map variants flag, as they lacked map variants.
/:cl:
=> Fixes merc armors being broken by non-existent map variants

code/modules/projectiles/guns/shotguns.dm
This is meant to bring the firing rate of the SH-35 a bit closer to what you'd expect from someone skilled enough to slamfire. Req shotties are still like, four times faster.
SH-35 has a 2 second refire delay, currently. It doesn't need to be like that, and it was implied to me by Jas that it's not supposed to be. This is my solution, without making it outshine the req shotguns.
:cl:
/:cl:
=> Sets fire and pump delay for the SH-35 to 8 deciseconds

code/modules/clothing/suits/marine_armor.dm
Certain M3 armors lack map variant sprites because they were replaced with later iterations of armor and/or made unavailable at some point in TGMC coding history. This disables the map variant system for the whole M3 pattern.
They aren't customizable to begin with, currently, and there's no one-line-fits-all solution other than disabling this. Occam's Razor.
:cl:
del: Disables the map variants for M3 armor and any subtype of it by default.
/:cl:
=> M3 armor is no longer affected by the map variant system

code/modules/reqs/supplypacks.dm
Adds a new fancy Freelancer styled kit to the Import section for 45 points. This includes a the TX-55, a few spare AR mags for it and the Freelancer leader's version of their vest, which comes with a Valkyrie module.
Well, it makes the TX-54 slightly more bareable? But aside from that, it gives an AR styled alternative to the V51B kit.
In terms of points, all the items in theory would add up to 47(Not counting the free extra 3 mags.), so it comes with a nice discount!
30 for the TX-54.
5 for the imported rifle.
12 for the Valkyrie module.
:cl:
add: Adds a new supply pack.
/:cl:
=> Freelancer Kit!

code/modules/reagents/reactions/medical.dm, code/modules/reagents/reagents/medical.dm
Several medical chems require lemoline to make, which in turn can only be made by combining lemoline with larval jelly, which isn't really obtainable in our codebase, or by ordering it from req, which nobody bothers with doing. This PR alters several recipes to make them slightly less of a pain in the ass to mix, and even adds a recipe for Russian Red. 
Maybe shipdocs will have a reason to do chemistry now, and maybe corpsmen can refill their advanced meds either on the ship or in the groundmap medical lab.
:cl:
qol: Dexalin recipe now requires 1u of iron instead of 0.1 phoron. Catalyst unchanged.
qol: Dermaline and Meralyne recipes now require 1u clonexadone instead of 1u lemoline, and 5u phoron as a catalyst
qol: Ryetalyn recipe now requires 1u sterilizine instead of 1u lemoline.
qol: …
=> Various medical recipe changes. Adds Russian Red recipe.

tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Reverted due to ongoing bluescreens when opening setup. Further PRs for this name change will be ignored until the actual cause is found out and corrected.
=> Revert "Fixes a TGUI bug"

code/datums/skills.dm
Changes the Standard Man at Arms to have engi engi skill. Meaning they can repair plasteel cades without fumbling, etc, etc.
I 'unno, I don't play the role. The others said it was a good idea.
=> Updates one line for the Man at Arms, allowing for fast plasteel repairs.

code/modules/reqs/supplypacks.dm
As the Leader freelancer armor is no longer different to the standard variant, the price should reflect that.
We could've put the valk back on but uh...Then we'd just be with a cheaper B18.
You still get a beret that's armored. That's good, right?
=> Updates the AR55 pack's pricing for the unteenth time.

code/game/turfs/walls/wall_types.dm
see title
duh
no more weird no boarders
changes image size of titles to 608x480
adds borders to the two existing ones
changes walltypes.dm in a way I dont know how to discribe
changes names in titles.dmi so that they actually work (in acordancce to the walltypes.dm changes)
=> fixes title screenss

_maps/shuttles/distress_upgrade.dmm, code/__DEFINES/shuttles.dm, code/datums/emergency_calls/supplies.dm, code/datums/shuttles.dm, code/game/area/areas/shuttles.dm, code/game/objects/structures/dropship_equipment.dm
Been trying map stuff recently. Might be useful to use in certain missions, as normally if you'd delete a wall, the floor would never return.
You can access this dropship variant trough the supply ERT.
Well. It allows for more variety with dropships!
:cl:
/:cl:
=> Adds a new ERT dropship variant

code/datums/components/suit_autorepair.dm, code/modules/clothing/modular_armor/attachments/modules.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/reqs/supplypacks.dm, tgmc.dme
The Huldra Autorepair module is a new design in a similar vein to the Valkyrie Automedic, designed exclusively for use by TGMC combat robots.
Besides being a requested feature for some time now, the Huldra grants a heal over time to robots that is comparable to the classic Bicaridine Kelotane Tricordrazine Tramadol premed mix that human marines enjoy the use of. Unlike BKTT, the Huldra is only accessible from Req, with a 15 point price tag. This cheap price is to offset the fact that humans have access to good regenerative chems from the get-go.
:cl:
add: Added Huldra Autorepair module, available from req.
/:cl:
=> Adds Huldra Autorepair module

code/modules/clothing/modular_armor/modular.dm
I noticed that non-modular armors could do this, but modular ones could not. Didn't make sense to me.
Medics can choose to take the pointman belt without having to either give up a vital piece of storage equipment or go without armor modules.
:cl:
fix: Modular armor can now have a pointman belt in the suit storage slot, for those builds that need the belt slot for something else.
/:cl:
=> Allows modular armor to have pointman belt in the exosuit storage slot

code/modules/projectiles/magazines/specialist.dm
Fixes a bug where SVD ammo isn't accepted by the T-74 belt
:cl:
fix: The ammo type datum for 7.62x54mmR now has the correct caliber.
/:cl:
=> quick fix for 7.62x54 in marksman belt.
